runtime: python27
api_version: 1
threadsafe: true

service: app

handlers:
- url: /app/
  static_files: dvc-frontend/index.html
  upload: dvc-frontend/index.html
- url: /app/
  static_dir: dvc-frontend
