runtime: python38
#api_version: 1
#threadsafe: true ---removed in python38

service: default

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /(.*\.js)
  static_files: \1
  upload: (.*\.js)
  mime_type: application/javascript
  require_matching_file: true
  secure: always

- url: /(.*\.css)
  static_files: \1
  upload: (.*\.css)
  mime_type: text/css
  require_matching_file: true
  secure: always

- url: /assets/
  static_dir: assets/
  require_matching_file: true
  secure: always

- url: /(.*)
  static_files: index.html
  upload: index.html
  secure: always



#runtime: python27
#api_version: '1'
#env: standard
#threadsafe: true
#instance_class: F1
#handlers:
#  - url: /
#    secure: always
#    application_readable: false
#    static_files: dvc-frontend/index.html
#    require_matching_file: false
#    upload: dvc-frontend/index.html
#  - url: /(.*)
#    secure: always
#    application_readable: false
#    static_files: dvc-frontend/\1
#    require_matching_file: true
#    upload: dvc-frontend/.*
#  - url: /(.*)
#    secure: always
#    application_readable: false
#    static_files: dvc-frontend/index.html
#    require_matching_file: false
#    upload: dvc-frontend/index.html
#automatic_scaling:
#  min_idle_instances: automatic
#  max_idle_instances: automatic
#  min_pending_latency: automatic
#  max_pending_latency: automatic
#network: {}
